#define CLASS                            1
#define ID                               2
#define LD                               3
#define RD                               4
#define LP                               5
#define RP                               6
#define TEXT                             7
#define INTEGER                          8
#define DOT                              9
#define PLUS                            10
#define MULTI                           11
#define DIVIDED                         12
#define MINUS                           13
#define SEMI                            14
#define COMMA                           15
#define INT                             16
#define STRING                          17
#define EQ                              18
#define NEW                             19
#define RETURN                          20
#define PUBLIC                          21
#define PROTECTED                       22
#define PRIVATE                         23
#define VOID                            24
#define EXTENDS                         25
